/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import logic.CodeGenerator;
import model.AFD;
import model.LamdaState;

/**
 *
 * @author luis_
 */
public class AFDView extends javax.swing.JFrame {
    
    AFD automaton;
    String code = "";
    /**
     * Creates new form AFDView
     */
    public AFDView(AFD automaton) {
        this.automaton = automaton;
        
        DefaultTableModel tModel = new DefaultTableModel(automaton.states.size(), automaton.symbols.length() + 2);
        setTableColumnIdentifiers(tModel, automaton.symbols);
        initComponents();
        tblAutomaton.setModel(tModel);
        setTableRows(automaton.states, tModel);
        this.setVisible(true);
    }
    
    public void setTableColumnIdentifiers(DefaultTableModel tModel, String symbols)
    {
        String[] headers = new String[symbols.length() + 2];
        headers [0] = "";
        headers [headers.length - 1] = "┤";
        
        for (int i = 1; i < headers.length - 1; i++)
        {
            headers[i] = symbols.substring(i-1,i);
        }
        tModel.setColumnIdentifiers(headers);
    }
    
    public void setTableRows (List<LamdaState> states, DefaultTableModel tModel)
    {
        for (int i = 0; i < states.size(); i++)
        {
            LamdaState state = states.get(i);
            tModel.setValueAt(i, i, 0);
            for (int j = 1; j < tModel.getColumnCount() - 1; j++)
            {
                tModel.setValueAt(state.transitions.get(tModel.getColumnName(j)), i, j);
            }
            tModel.setValueAt(state.isUptakingState ? "1" : "0", i, tModel.getColumnCount() - 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutomaton = new javax.swing.JTable();
        btnGenerateProgram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblAutomaton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutomaton);

        btnGenerateProgram.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerateProgram.setText("Generar programa del autómata");
        btnGenerateProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerateProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateProgramActionPerformed
        this.code = CodeGenerator.generateCode(automaton.states, automaton.symbols);
        Code codeView = new Code(code);
    }//GEN-LAST:event_btnGenerateProgramActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateProgram;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutomaton;
    // End of variables declaration//GEN-END:variables
}
